- hosts: web
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  vars:
    playbook_version: v1
  vars_files:
    - copyrights.yml
    - web.yml
  vars_prompt:
    - name: Web_Domain
      prompt: Web Domain
  tasks: 
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      async: 300
      poll: 3
      notify: Restart HTTPD
  handlers: 
    - name: Restart HTTPD
      action: service name=httpd state=restarted

