---

- hosts: app
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: date/time stamp for when the playbook starts
      raw: /usr/bin/date > /home/ansible/playbook_start.log
    - name: Installing the Apache web server
      yum: pkg=httpd state=latest
    - name: start the web service
      service: name=httpd state=restarted
    - name: verify that the web service is running
      command: systemctl status httpd
      register: result
    - debug: var=result
    - name: Install client software - telnet
      yum : pkg=telnet state=latest
    - name: Install client software - lynx
      yum: pkg=lynx state=latest
    - name: log all the packages install on the system
      raw: yum list installed > /home/ansible/installed.log
    - name: date/time stamp for when the playbook ends
      raw: /usr/bin/date > /home/ansible/playbook_end.log

